[project]
name = "fullstack-api-service-with-ecs"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "anydi>=0.47.0",
    "fastapi>=0.116.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.9",
]
