name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
      - uv.lock
      - "app/**"
      - "!*.md"

  pull_request:
    branches:
      - main
    paths:
      - pyproject.toml
      - uv.lock
      - "app/**"
      - "!*.md"
      - ".github/workflows/ci.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install ruff
        uses: astral-sh/ruff-action@v3

      - name: Run ruff
        run: ruff check --output-format=github app/

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run tests
        run: uv run pytest
